### ISSUE TITLE
SyntaxError trying run file

### ISSUE THREAD

**Issue by rvcristiand** [WittmannF/jupyter-translate#1]
Hi ! I cloned your repo and tried run `python jupyter_translate.py playground.ipynb --languaje 'en'` and I got the following error

`File "/home/rvcristiand/Documents/jupyter-translate/jupyter_translate.py", line 23
 list_to_gen = lambda: [(yield x) for x in replacement_list]
                                   ^
 SyntaxError: 'yield' inside list comprehension
`

**Comment by dimi1engineer** [comment]
I have the same problem.

**Comment by gachet** [comment]
Same problem, also running cells on playground.ipynb in colab does not work.
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ehultee** [comment]
The SyntaxError can be corrected by simply removing the `yield` statement, so line 23 becomes
```
        list_to_gen = lambda: [(yield x) for x in replacement_list]
```

The AttributeError is a problem with `googletrans`, not with this script.  You can correct it by [installing an alpha version of `googletrans`](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group).  

We just made a PullRequest to fix both of these.
