### ISSUE TITLE
Add loader.

### ISSUE THREAD

**Issue by ekp1k80** [WittmannF/jupyter-translate#5]
Hey Man, i uses to transplante fast ai todo. It's working fine así i can see. I would just add a loader. Like printing the total numbers of cells AND the cell by cell like
Translating cell 3 of 192 etc etc.
I didnt think it was working until i added

**Comment by andrebelem** [comment]
Hellp @ekp1k80  
We used tqdm to show progress and now it's counting the number of cells in translator.
